icondir = $(datadir)/icons
nobase_icon_DATA = \
	hicolor/16x16/apps/xpad.png \
	hicolor/22x22/apps/xpad.png \
	hicolor/32x32/apps/xpad.png \
	hicolor/48x48/apps/xpad.png \
	hicolor/64x64/apps/xpad.png \
	hicolor/96x96/apps/xpad.png \
	hicolor/128x128/apps/xpad.png \
	hicolor/scalable/apps/xpad.svg

pixmapdir = $(datadir)/pixmaps
pixmap_DATA = hicolor/48x48/apps/xpad.png

EXTRA_DIST = xpad-debian.xpm sticky.xpm xpad.xpm
