dnl Process this file with autoconf to produce a configure script.
dnl xpad version
dnl line taken from aterm project
VERSION=`sed -n -e 's/^.*VERSION.*"\(.*\)"$/\1/p' src/defines.h`

AC_INIT([src/fio.c])
AC_CONFIG_AUX_DIR(scripts)
AM_INIT_AUTOMAKE(xpad, 1.9)
AM_CONFIG_HEADER(src/config.h:config.h.in)
AC_PROG_MAKE_SET

AC_SUBST(VERSION)

dnl Checks for programs.
AC_PROG_CC
AC_PROG_INSTALL

dnl Checks for libraries.

dnl Checks for header files.
AC_HEADER_STDC
AC_CHECK_HEADERS(unistd.h)

dnl Checks for typedefs, structures, and compiler characteristics.
AC_C_CONST
AC_TYPE_SIZE_T
AC_HEADER_TIME

dnl Checks for library functions.
AC_TYPE_SIGNAL
AC_CHECK_FUNCS(mkdir select socket strcspn strstr strtol)

ALL_LINGUAS=""
AM_GNU_GETTEXT
AC_OUTPUT(Makefile src/Makefile doc/Makefile images/Makefile intl/Makefile po/Makefile.in m4/Makefile)
