.\"                                      Hey, EMACS: -*- nroff -*-
.TH XPAD 1 "January  7, 2002"
.SH NAME
xpad \- A "post-it" note system for GTK+ 2.0
.SH SYNOPSIS
.B xpad
.RI [OPTIONS]
.SH DESCRIPTION
A sticky note system for GTK+ 2.0.
.PP
.SH OPTIONS
.TP
.B \-V, \-\-version
Display version information.
.TP
.B \-h, \-\-help
Display usage information.
.TP
.B \-v N, \-\-verbosity=N
Change amount of output.  0 is none; 1 is moderate; 2 is debug.  Default is 0.
.SH AUTHOR
Written by Michael Terry <msterry@student.umass.edu>.
