.\"                                      Hey, EMACS: -*- nroff -*-
.TH XPAD 1 "November 23, 2002"
.SH NAME
xpad \- A "post-it" note system for GTK+ 2.0
.PP
.SH SYNOPSIS
.B xpad
.RI [OPTIONS]
.PP
.SH DESCRIPTION
A sticky note system for GTK+ 2.0.
.PP
.SH OPTIONS
.TP
.B \-V, \-\-version
Display version information.
.TP
.B \-h, \-\-help
Display usage information.
.TP
.B \-v N, \-\-verbosity=N
Change amount of output.  0 is none; 1 is moderate; 2 is debug.  Default is 0.
.TP
.B \-n, \-\-new
Open a new pad.
.TP
.B \-\-nonew
Prevents xpad from making new pads.
.TP
.B \-q, \-\-quit
Quits all xpad sessions.
.TP
.B \-l, \-\-list
Lists the titles of all pads.
.TP
.B \-s N, \-\-show=N
Brings the Nth pad (1-based) to the foreground.
.TP
.B \-\-showall
Brings all pads to the foreground.
.PP
.SH AUTHOR
Written by Michael Terry <mikix@users.sourceforge.net>.
